spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/rppg
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 600000
      idle-timeout: 300000
      pool-name: YouziHikariPool
  sql:
    init:
      mode: always
      schema-locations: classpath:init-data.sql
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  grpc:
    client:
      channels:
        frame-analysis:
          address: static://localhost:50051
          negotiation-type: PLAINTEXT

